### ISSUE TITLE
myGpuFeatures,ImportError: DLL load failed: 找不到指定的模块。

### ISSUE THREAD

**Issue by monkeycc** [Keep-Passion/ImageStitch#29]
解压了在根目录 myGpuFeatures
D:\ImageStitch\myGpuFeatures

python Main.py
```
Traceback (most recent call last):
  File "Main.py", line 1, in <module>
    from Stitcher import Stitcher
  File "D:\ImageStitch\Stitcher.py", line 10, in <module>
    import ImageUtility as Utility
  File "D:\ImageStitch\ImageUtility.py", line 4, in <module>
    from myGpuFeatures import myGpuFeatures
ImportError: DLL load failed: 找不到指定的模块。
```

**Comment by Keep-Passion** [comment]
你好，这个开源代码库我已经不在维护了，这里面的gpu加速不稳定，适配机型少，如有应用需求，请在最新版web服务下载试用，你觉得用的好再跟我聊商务，谢谢。http://microstitch.ustb-ai3d.cn/

**Comment by loganzhang4** [comment]
大佬你好，我也是出现这个问题，您还方便提供相关支持吗，我想复现您的程序
