### ISSUE TITLE
How i can run this project on ubuntu.

### ISSUE THREAD

**Issue by kuldeep203** [Keep-Passion/ImageStitch#30]
I am scanning the blood slide and want to stich together, so how i can stich all of them.

**Comment by Colin-Jing** [comment]
Download the required Python dependency package, change the data set in mian.py to your data set,  and then you can run it.

**Comment by kuldeep203** [comment]
after installing all packages i run the main .py but i got the following error.
ImportError: cannot import name 'myGpuFeatures' from 'myGpuFeatures' (unknown location)

**Comment by Colin-Jing** [comment]
You should unzip the myFeatures.rar file first

**Comment by kuldeep203** [comment]
i unzip the myFeatures.rar and find the following packages.
/home/kuldeep/ImageStitch/myGpuFeatures/myGpuFeatures.pyd
/home/kuldeep/ImageStitch/myGpuFeatures/opencv_aruco331.dll
/home/kuldeep/ImageStitch/myGpuFeatures/opencv_bgsegm331.dll
/home/kuldeep/ImageStitch/myGpuFeatures/opencv_bioinspired331.dll
/home/kuldeep/ImageStitch/myGpuFeatures/opencv_ccalib331.dll
/home/kuldeep/ImageStitch/myGpuFeatures/opencv_core331.dll
/home/kuldeep/ImageStitch/myGpuFeatures/opencv_cudaarithm331.dll
/home/kuldeep/ImageStitch/myGpuFeatures/opencv_cudacodec331.dll
/home/kuldeep/ImageStitch/myGpuFeatures/opencv_cudafeatures2d331.dll
/home/kuldeep/ImageStitch/myGpuFeatures/opencv_cudafilters331.dll
/home/kuldeep/ImageStitch/myGpuFeatures/opencv_cudawarping331.dll
/home/kuldeep/ImageStitch/myGpuFeatures/opencv_cudev331.dll
/home/kuldeep/ImageStitch/myGpuFeatures/opencv_datasets331.dll
/home/kuldeep/ImageStitch/myGpuFeatures/opencv_dpm331.dll
/home/kuldeep/ImageStitch/myGpuFeatures/opencv_face331.dll
/home/kuldeep/ImageStitch/myGpuFeatures/opencv_features2d331.dll
/home/kuldeep/ImageStitch/myGpuFeatures/opencv_flann331.dll
/home/kuldeep/ImageStitch/myGpuFeatures/opencv_fuzzy331.dll
/home/kuldeep/ImageStitch/myGpuFeatures/opencv_hdf331.dll
/home/kuldeep/ImageStitch/myGpuFeatures/opencv_highgui331.dll
/home/kuldeep/ImageStitch/myGpuFeatures/opencv_img_hash331.dll
/home/kuldeep/ImageStitch/myGpuFeatures/opencv_imgproc331.dll
/home/kuldeep/ImageStitch/myGpuFeatures/opencv_line_descriptor331.dll
/home/kuldeep/ImageStitch/myGpuFeatures/opencv_ml331.dll
/home/kuldeep/ImageStitch/myGpuFeatures/opencv_objdetect331.dll
/home/kuldeep/ImageStitch/myGpuFeatures/opencv_optflow331.dll
/home/kuldeep/ImageStitch/myGpuFeatures/opencv_phase_unwrapping331.dll
/home/kuldeep/ImageStitch/myGpuFeatures/opencv_plot331.dll
/home/kuldeep/ImageStitch/myGpuFeatures/opencv_reg331.dll
/home/kuldeep/ImageStitch/myGpuFeatures/opencv_rgbd331.dll
/home/kuldeep/ImageStitch/myGpuFeatures/opencv_saliency331.dll
/home/kuldeep/ImageStitch/myGpuFeatures/opencv_shape331.dll
/home/kuldeep/ImageStitch/myGpuFeatures/opencv_stereo331.dll
/home/kuldeep/ImageStitch/myGpuFeatures/opencv_structured_light331.dll
/home/kuldeep/ImageStitch/myGpuFeatures/opencv_superres331.dll
/home/kuldeep/ImageStitch/myGpuFeatures/opencv_surface_matching331.dll
/home/kuldeep/ImageStitch/myGpuFeatures/opencv_text331.dll
/home/kuldeep/ImageStitch/myGpuFeatures/opencv_video331.dll
/home/kuldeep/ImageStitch/myGpuFeatures/opencv_videoio331.dll
/home/kuldeep/ImageStitch/myGpuFeatures/opencv_xfeatures2d331.dll
/home/kuldeep/ImageStitch/myGpuFeatures/opencv_xobjdetect331.dll
/home/kuldeep/ImageStitch/myGpuFeatures/opencv_xphoto331.dll
/home/kuldeep/ImageStitch/myGpuFeatures/tbb.dll

but again getting the same error.

**Comment by Colin-Jing** [comment]
Comment out the fourth line of ImageUtility.py and try again

**Comment by kuldeep203** [comment]
Traceback (most recent call last):
  File "/home/kuldeep/ImageStitch/Main.py", line 54, in <module>
    stitchWithFeature()
  File "/home/kuldeep/ImageStitch/Main.py", line 26, in stitchWithFeature
    stitcher.imageSetStitchWithMutiple(projectAddress, outputAddress, 1, stitcher.calculateOffsetForFeatureSearchIncre,
  File "/home/kuldeep/ImageStitch/Stitcher.py", line 172, in imageSetStitchWithMutiple
    result = self.flowStitchWithMutiple(fileList, caculateOffsetMethod)
  File "/home/kuldeep/ImageStitch/Stitcher.py", line 107, in flowStitchWithMutiple
    (status, stitchResult) = self.flowStitch(fileList[startNum: totalNum], caculateOffsetMethod)
  File "/home/kuldeep/ImageStitch/Stitcher.py", line 56, in flowStitch
    self.printAndWrite("Stitching the directory which have " + str(fileList[0]))
IndexError: list index out of range

Process finished with exit code 1
Done the same thing as you suggest but again getting the error as shown above.

**Comment by Colin-Jing** [comment]
Please make sure that the location of the images folder is consistent with the location of the image organization in the demoImages folder
